### ISSUE TITLE
No longer working!!

### ISSUE THREAD

**Issue by mitbr1** [alexgladd/bm-hotgroups#23] opened 2020-07-17 16:22 UTC
Hi Alex thanks for this app I use it all the time!!
As of July 17 it no longer is working. The app loads fine but no data is shown from Brandmiester.
Tried on Chrome,Firefox.Android phone none work !!
Thanks Tim

**Comment by billz1234** [comment] 2020-07-18 23:12
As of July 17 it no longer is working. The app loads fine but no data is shown from Brandmiester.
Tried on Chrome,Firefox.Android phone none work !!

**Comment by delight-f** [comment] 2021-02-15 12:34
Hi Alex,

Still not working. Is this being actively developed still?

**Comment by alexgladd** [comment] 2021-02-18 08:45
Hi folks,

Thank you for using my app, and I appreciate you taking the time to file these reports. I believe the Brandmeister network operators made a change to their "last heard" API so that it's no longer accessible to third-party apps, but I haven't had a chance to fully investigate this yet.  I'd be happy to accept a pull request if anyone has time to take a look; I'm not sure when I'll be able to get to this myself.

**Comment by alexgladd** [comment] 2021-04-12 12:34
I took a quick look at this in production today. Thankfully, the problem appears to not be related to an API accessibility problem.  It looks like the format of the messages delivered by the last heard websocket has changed.  That may indicate that this is a simple fix.  I should get some time this month to take a closer look.

**Comment by alexgladd** [comment] 2021-04-18 19:37
Good news! I can confirm that I have a fix for this working locally. It looks like the network made some changes to the events that come across the API so my existing aggregation code wasn't working anymore (hence, nothing showing up on the page). I've fixed this, but I'm still working on making sure I understand all of the characteristics of the updated API events so that I can verify I'm aggregating things correctly. Hope to have the fix published soon.

**Closed as completed** 2021-04-25 12:26 UTC
Labels: bug

**Comment by alexgladd** [comment] 2021-04-25 12:36
@mitbr1 @billz1234 @delight-f Happy to let you know that I just deployed an updated version of the app that fixes this issue and also add a new "Currently Active" section. I hope you all continue to enjoy using the app, and thanks again for providing feedback.
